import { mastra } from '@/src/mastra';
import { google } from 'googleapis';

/**
 * Intelligent Search Service
 * 
 * Uses the Gmail Search Agent to convert natural language queries into Gmail API queries
 * and then executes the search to return matching emails.
 * 
 * Note: This service runs server-side in API routes and uses the Google API client directly.
 */

export interface IntelligentSearchResult {
  query: string;
  labelIds: string[];
  explanation: string;
  detectedParams: {
    from?: string;
    to?: string;
    subject?: string;
    folder?: string;
    hasAttachment?: boolean;
    isUnread?: boolean;
    isStarred?: boolean;
    dateRange?: string;
    keywords?: string[];
  };
  messages: any[];
}

class IntelligentSearchService {
  private accessToken: string | null = null;

  /**
   * Set the access token for Gmail API calls
   */
  setAccessToken(token: string) {
    this.accessToken = token;
  }

  private getAccessToken(): string {
    if (!this.accessToken) {
      throw new Error('Access token not set. Call setAccessToken() first.');
    }
    return this.accessToken;
  }

  /**
   * Search emails using natural language query
   * 
   * Example:
   * - "show me emails with birthday from niti in my primary inbox"
   * - "unread emails from john with attachments"
   * - "emails about project from last week"
   */
  async search(naturalLanguageQuery: string, maxResults: number = 30): Promise<IntelligentSearchResult> {
    console.log('[INTELLIGENT SEARCH] Processing query:', naturalLanguageQuery);

    // Get the Gmail Search Agent
    const agent = mastra.getAgent('gmailSearchAgent');

    // Use the agent to generate the Gmail query
    const agentResponse = await agent.generate(
      `Convert this natural language search request into a Gmail API query string. 
      
User request: "${naturalLanguageQuery}"

Return ONLY a JSON object with this exact structure:
{
  "query": "the Gmail query string",
  "labelIds": ["INBOX"],
  "explanation": "explanation of the query construction",
  "detectedParams": {
    "from": "sender if detected",
    "to": "recipient if detected",
    "subject": "subject keywords if detected",
    "folder": "folder name if detected",
    "hasAttachment": true/false,
    "isUnread": true/false,
    "isStarred": true/false,
    "dateRange": "date range if detected",
    "keywords": ["other", "keywords"]
  }
}

Return ONLY the JSON object, no markdown, no code blocks.`,
      {
        memory: {
          resource: 'intelligent-search',
          thread: 'search-session',
        },
      }
    );

    // Parse the agent's response
    let searchConfig: {
      query: string;
      labelIds?: string[];
      explanation?: string;
      detectedParams?: any;
    };

    try {
      // Try to parse JSON from the response
      const responseText = agentResponse.text || agentResponse.toString();
      // Extract JSON if it's wrapped in markdown code blocks
      const jsonMatch = responseText.match(/```json\s*([\s\S]*?)\s*```/) || 
                        responseText.match(/```\s*([\s\S]*?)\s*```/) ||
                        [null, responseText];
      const jsonStr = jsonMatch[1] || responseText;
      searchConfig = JSON.parse(jsonStr.trim());
    } catch (error) {
      console.error('[INTELLIGENT SEARCH] Failed to parse agent response:', error);
      console.log('[INTELLIGENT SEARCH] Raw response:', agentResponse);
      
      // Fallback: try to extract query from response text
      const fallbackQuery = this.extractQueryFromText(agentResponse.text || agentResponse.toString());
      searchConfig = {
        query: fallbackQuery,
        labelIds: [],
        explanation: 'Fallback extraction from agent response',
        detectedParams: {},
      };
    }

    console.log('[INTELLIGENT SEARCH] Generated query:', searchConfig.query);
    console.log('[INTELLIGENT SEARCH] Label IDs:', searchConfig.labelIds);

    // Execute the search using the Gmail client
    const messages = await this.executeSearch(
      searchConfig.query,
      searchConfig.labelIds || [],
      maxResults,
      this.getAccessToken()
    );

    return {
      query: searchConfig.query,
      labelIds: searchConfig.labelIds || [],
      explanation: searchConfig.explanation || 'Query generated by Gmail Search Agent',
      detectedParams: searchConfig.detectedParams || {},
      messages,
    };
  }

  /**
   * Execute the Gmail search with the generated query
   * Uses Google API client directly (server-side)
   */
  private async executeSearch(query: string, labelIds: string[], maxResults: number, accessToken: string): Promise<any[]> {
    try {
      // Create OAuth2 client and set credentials
      const auth = new google.auth.OAuth2();
      auth.setCredentials({ access_token: accessToken });

      // Create Gmail API client
      const gmail = google.gmail({ version: 'v1', auth });

      // First, get the list of message IDs
      const listResponse = await gmail.users.messages.list({
        userId: 'me',
        q: query,
        labelIds: labelIds.length > 0 ? labelIds : undefined,
        maxResults,
      });

      const messageList = listResponse.data.messages || [];
      console.log('[INTELLIGENT SEARCH] Found messages:', messageList.length);

      if (messageList.length === 0) {
        return [];
      }

      // Fetch full message details for each message
      const messages = await Promise.all(
        messageList.map(async (msg: any) => {
          try {
            const fullMessage = await gmail.users.messages.get({
              userId: 'me',
              id: msg.id!,
              format: 'metadata',
              metadataHeaders: ['From', 'To', 'Subject', 'Date'],
            });
            return fullMessage.data;
          } catch (error) {
            console.error(`[INTELLIGENT SEARCH] Failed to fetch message ${msg.id}:`, error);
            return null;
          }
        })
      );

      return messages.filter((m): m is any => m !== null);
    } catch (error) {
      console.error('[INTELLIGENT SEARCH] Search execution failed:', error);
      throw error;
    }
  }

  /**
   * Quick rule-based search without AI agent
   * Uses regex patterns to extract query components for simple queries
   * Faster execution (no LLM call)
   */
  async quickSearch(naturalLanguageQuery: string, maxResults: number = 30): Promise<IntelligentSearchResult> {
    console.log('[INTELLIGENT SEARCH] Quick search for:', naturalLanguageQuery);

    const detectedParams: IntelligentSearchResult['detectedParams'] = {};
    const queryParts: string[] = [];
    const labelIds: string[] = [];

    const query = naturalLanguageQuery.toLowerCase();

    // Extract sender (from:)
    const fromMatch = query.match(/from\s+([\w.@]+)|emails?\s+(?:from|by)\s+([\w.@]+)/i);
    if (fromMatch) {
      const sender = fromMatch[1] || fromMatch[2];
      detectedParams.from = sender;
      queryParts.push(`from:${sender}`);
    }

    // Extract recipient (to:)
    const toMatch = query.match(/to\s+([\w.@]+)|sent\s+to\s+([\w.@]+)/i);
    if (toMatch) {
      const recipient = toMatch[1] || toMatch[2];
      detectedParams.to = recipient;
      queryParts.push(`to:${recipient}`);
    }

    // Extract subject keywords
    const subjectMatch = query.match(/(?:about|subject|regarding)\s+["']?([^"']+?)["']?(?:\s+(?:from|in|with|has|is)\s+|\s*$)/i);
    if (subjectMatch) {
      const subject = subjectMatch[1].trim();
      detectedParams.subject = subject;
      queryParts.push(`subject:${subject}`);
    }

    // Extract folder/label
    const folderMatch = query.match(/in\s+(?:my\s+)?(?:primary\s+)?(inbox|sent|drafts?|spam|trash|important|starred|archive)/i);
    if (folderMatch) {
      const folder = folderMatch[1].toLowerCase();
      detectedParams.folder = folder;
      if (folder === 'inbox') {
        queryParts.push('in:inbox');
        labelIds.push('INBOX');
      } else if (folder === 'sent') {
        queryParts.push('in:sent');
      } else if (folder === 'draft' || folder === 'drafts') {
        queryParts.push('in:draft');
      } else if (folder === 'spam') {
        queryParts.push('in:spam');
      } else if (folder === 'trash') {
        queryParts.push('in:trash');
      } else if (folder === 'important') {
        queryParts.push('in:important');
        labelIds.push('IMPORTANT');
      } else if (folder === 'starred') {
        queryParts.push('is:starred');
        detectedParams.isStarred = true;
      }
    }

    // Check for unread status
    if (query.includes('unread')) {
      queryParts.push('is:unread');
      detectedParams.isUnread = true;
    }

    // Check for starred status
    if (query.includes('starred') || query.includes('favorite')) {
      queryParts.push('is:starred');
      detectedParams.isStarred = true;
    }

    // Check for attachments
    const attachmentMatch = query.match(/(?:with|has|have)\s+(?:an?\s+)?attachment|attached/i);
    if (attachmentMatch) {
      queryParts.push('has:attachment');
      detectedParams.hasAttachment = true;

      // Check for specific file types
      const pdfMatch = query.match(/pdf|\.pdf/i);
      if (pdfMatch) {
        queryParts.push('filename:pdf');
      }
      const imageMatch = query.match(/image|picture|photo|\.jpg|\.png|\.gif/i);
      if (imageMatch) {
        queryParts.push('filename:jpg OR filename:png OR filename:gif');
      }
    }

    // Extract date ranges
    const lastWeekMatch = query.match(/last\s+week/i);
    if (lastWeekMatch) {
      queryParts.push('newer_than:7d');
      detectedParams.dateRange = 'last 7 days';
    }
    const lastMonthMatch = query.match(/last\s+month/i);
    if (lastMonthMatch) {
      queryParts.push('newer_than:30d');
      detectedParams.dateRange = 'last 30 days';
    }

    // Extract remaining keywords (not already captured)
    const keywords: string[] = [];
    const words = query.split(/\s+/);
    const stopWords = ['emails', 'email', 'from', 'to', 'in', 'my', 'with', 'has', 'have', 'is', 'are', 'the', 'a', 'an', 'about', 'show', 'me', 'search', 'find', 'get', 'all', 'any'];
    
    for (const word of words) {
      const cleanWord = word.replace(/[^\w]/g, '');
      if (cleanWord.length > 2 && !stopWords.includes(cleanWord) && !queryParts.some(part => part.includes(cleanWord))) {
        keywords.push(cleanWord);
      }
    }
    
    if (keywords.length > 0) {
      detectedParams.keywords = keywords;
      // Add keywords that aren't already in the query
      const uniqueKeywords = keywords.filter(kw => !queryParts.some(part => part.toLowerCase().includes(kw.toLowerCase())));
      if (uniqueKeywords.length > 0) {
        queryParts.push(uniqueKeywords.join(' '));
      }
    }

    // Build final query
    const finalQuery = queryParts.join(' ') || naturalLanguageQuery;

    console.log('[INTELLIGENT SEARCH] Quick generated query:', finalQuery);

    // Execute the search
    const messages = await this.executeSearch(finalQuery, labelIds, maxResults, this.getAccessToken());

    return {
      query: finalQuery,
      labelIds,
      explanation: `Rule-based query: ${finalQuery}`,
      detectedParams,
      messages,
    };
  }

  /**
   * Fallback method to extract query from plain text response
   */
  private extractQueryFromText(text: string): string {
    // Look for patterns like "query: ..." or the query operators
    const queryMatch = text.match(/query[:\s]+([^\n]+)/i);
    if (queryMatch) {
      return queryMatch[1].trim();
    }

    // Look for Gmail query operators in the text
    const operators = ['from:', 'to:', 'subject:', 'in:', 'is:', 'has:', 'filename:', 'after:', 'before:', 'newer_than:', 'older_than:'];
    for (const op of operators) {
      if (text.includes(op)) {
        // Extract the part that looks like a query
        const opMatch = text.match(new RegExp(`(?:^|[\\s"'])(${op}[^\\s"'\n]+)`, 'i'));
        if (opMatch) {
          return opMatch[1].trim();
        }
      }
    }

    // Last resort: return the whole text as the query
    return text.trim().substring(0, 200);
  }
}

export const intelligentSearchService = new IntelligentSearchService();
