import { mastra } from '@/src/mastra';
import { gmail } from './gmail-client';

/**
 * Intelligent Search Service
 * 
 * Uses the Gmail Search Agent to convert natural language queries into Gmail API queries
 * and then executes the search to return matching emails.
 */

export interface IntelligentSearchResult {
  query: string;
  labelIds: string[];
  explanation: string;
  detectedParams: {
    from?: string;
    to?: string;
    subject?: string;
    folder?: string;
    hasAttachment?: boolean;
    isUnread?: boolean;
    isStarred?: boolean;
    dateRange?: string;
    keywords?: string[];
  };
  messages: any[];
}

class IntelligentSearchService {
  /**
   * Search emails using natural language query
   * 
   * Example:
   * - "show me emails with birthday from niti in my primary inbox"
   * - "unread emails from john with attachments"
   * - "emails about project from last week"
   */
  async search(naturalLanguageQuery: string, maxResults: number = 30): Promise<IntelligentSearchResult> {
    console.log('[INTELLIGENT SEARCH] Processing query:', naturalLanguageQuery);

    // Get the Gmail Search Agent
    const agent = mastra.getAgent('gmailSearchAgent');

    // Use the agent to generate the Gmail query
    const agentResponse = await agent.generate(
      `Convert this natural language search request into a Gmail API query string. 
      
User request: "${naturalLanguageQuery}"

Return ONLY a JSON object with this exact structure:
{
  "query": "the Gmail query string",
  "labelIds": ["INBOX"],
  "explanation": "explanation of the query construction",
  "detectedParams": {
    "from": "sender if detected",
    "to": "recipient if detected",
    "subject": "subject keywords if detected",
    "folder": "folder name if detected",
    "hasAttachment": true/false,
    "isUnread": true/false,
    "isStarred": true/false,
    "dateRange": "date range if detected",
    "keywords": ["other", "keywords"]
  }
}

Return ONLY the JSON object, no markdown, no code blocks.`,
      {
        memory: {
          resource: 'intelligent-search',
          thread: 'search-session',
        },
      }
    );

    // Parse the agent's response
    let searchConfig: {
      query: string;
      labelIds?: string[];
      explanation?: string;
      detectedParams?: any;
    };

    try {
      // Try to parse JSON from the response
      const responseText = agentResponse.text || agentResponse.toString();
      // Extract JSON if it's wrapped in markdown code blocks
      const jsonMatch = responseText.match(/```json\s*([\s\S]*?)\s*```/) || 
                        responseText.match(/```\s*([\s\S]*?)\s*```/) ||
                        [null, responseText];
      const jsonStr = jsonMatch[1] || responseText;
      searchConfig = JSON.parse(jsonStr.trim());
    } catch (error) {
      console.error('[INTELLIGENT SEARCH] Failed to parse agent response:', error);
      console.log('[INTELLIGENT SEARCH] Raw response:', agentResponse);
      
      // Fallback: try to extract query from response text
      const fallbackQuery = this.extractQueryFromText(agentResponse.text || agentResponse.toString());
      searchConfig = {
        query: fallbackQuery,
        labelIds: [],
        explanation: 'Fallback extraction from agent response',
        detectedParams: {},
      };
    }

    console.log('[INTELLIGENT SEARCH] Generated query:', searchConfig.query);
    console.log('[INTELLIGENT SEARCH] Label IDs:', searchConfig.labelIds);

    // Execute the search using the Gmail client
    const messages = await this.executeSearch(
      searchConfig.query,
      searchConfig.labelIds || [],
      maxResults
    );

    return {
      query: searchConfig.query,
      labelIds: searchConfig.labelIds || [],
      explanation: searchConfig.explanation || 'Query generated by Gmail Search Agent',
      detectedParams: searchConfig.detectedParams || {},
      messages,
    };
  }

  /**
   * Execute the Gmail search with the generated query
   */
  private async executeSearch(query: string, labelIds: string[], maxResults: number): Promise<any[]> {
    try {
      // First, get the list of message IDs
      const listResponse: any = await gmail.users.messages.list({
        q: query,
        labelIds: labelIds.length > 0 ? labelIds : undefined,
        maxResults,
      });

      const messageList = listResponse.messages || [];
      console.log('[INTELLIGENT SEARCH] Found messages:', messageList.length);

      if (messageList.length === 0) {
        return [];
      }

      // Fetch full message details for each message
      const messages = await Promise.all(
        messageList.map(async (msg: any) => {
          try {
            const fullMessage: any = await gmail.users.messages.get({
              id: msg.id,
              format: 'metadata',
              metadataHeaders: ['From', 'To', 'Subject', 'Date'],
            });
            return fullMessage;
          } catch (error) {
            console.error(`[INTELLIGENT SEARCH] Failed to fetch message ${msg.id}:`, error);
            return null;
          }
        })
      );

      return messages.filter((m): m is any => m !== null);
    } catch (error) {
      console.error('[INTELLIGENT SEARCH] Search execution failed:', error);
      throw error;
    }
  }

  /**
   * Fallback method to extract query from plain text response
   */
  private extractQueryFromText(text: string): string {
    // Look for patterns like "query: ..." or the query operators
    const queryMatch = text.match(/query[:\s]+([^\n]+)/i);
    if (queryMatch) {
      return queryMatch[1].trim();
    }

    // Look for Gmail query operators in the text
    const operators = ['from:', 'to:', 'subject:', 'in:', 'is:', 'has:', 'filename:', 'after:', 'before:', 'newer_than:', 'older_than:'];
    for (const op of operators) {
      if (text.includes(op)) {
        // Extract the part that looks like a query
        const opMatch = text.match(new RegExp(`(?:^|[\\s"'])(${op}[^\\s"'\n]+)`, 'i'));
        if (opMatch) {
          return opMatch[1].trim();
        }
      }
    }

    // Last resort: return the whole text as the query
    return text.trim().substring(0, 200);
  }
}

export const intelligentSearchService = new IntelligentSearchService();
