export interface WordEntry {
  word: string;
  category: string;
}

export const WORD_LIST: WordEntry[] = [
  // Animals
  { word: "ELEPHANT", category: "Animal" },
  { word: "GIRAFFE", category: "Animal" },
  { word: "PENGUIN", category: "Animal" },
  { word: "DOLPHIN", category: "Animal" },
  { word: "BUTTERFLY", category: "Animal" },
  { word: "KANGAROO", category: "Animal" },
  { word: "OCTOPUS", category: "Animal" },
  { word: "RHINOCEROS", category: "Animal" },
  { word: "CROCODILE", category: "Animal" },
  { word: "HIPPOPOTAMUS", category: "Animal" },
  { word: "CHIMPANZEE", category: "Animal" },
  { word: "PLATYPUS", category: "Animal" },
  { word: "FLAMINGO", category: "Animal" },
  { word: "HEDGEHOG", category: "Animal" },
  { word: "PEACOCK", category: "Animal" },
  
  // Countries
  { word: "AUSTRALIA", category: "Country" },
  { word: "BRAZIL", category: "Country" },
  { word: "CANADA", category: "Country" },
  { word: "DENMARK", category: "Country" },
  { word: "EGYPT", category: "Country" },
  { word: "FRANCE", category: "Country" },
  { word: "GERMANY", category: "Country" },
  { word: "INDIA", category: "Country" },
  { word: "JAPAN", category: "Country" },
  { word: "MEXICO", category: "Country" },
  { word: "NORWAY", category: "Country" },
  { word: "PORTUGAL", category: "Country" },
  { word: "SINGAPORE", category: "Country" },
  { word: "THAILAND", category: "Country" },
  { word: "VIETNAM", category: "Country" },
  
  // Food
  { word: "PIZZA", category: "Food" },
  { word: "HAMBURGER", category: "Food" },
  { word: "SPAGHETTI", category: "Food" },
  { word: "CHOCOLATE", category: "Food" },
  { word: "PANCAKE", category: "Food" },
  { word: "SANDWICH", category: "Food" },
  { word: "CROISSANT", category: "Food" },
  { word: "AVOCADO", category: "Food" },
  { word: "STRAWBERRY", category: "Food" },
  { word: "WATERMELON", category: "Food" },
  { word: "BLUEBERRY", category: "Food" },
  { word: "ASPARAGUS", category: "Food" },
  { word: "CUCUMBER", category: "Food" },
  { word: "RASPBERRY", category: "Food" },
  { word: "CINNAMON", category: "Food" },
  
  // Movies & Entertainment
  { word: "INCEPTION", category: "Movie" },
  { word: "TITANIC", category: "Movie" },
  { word: "GLADIATOR", category: "Movie" },
  { word: "FROZEN", category: "Movie" },
  { word: "JURASSIC", category: "Movie" },
  { word: "AVATAR", category: "Movie" },
  { word: "BATMAN", category: "Movie" },
  { word: "SUPERMAN", category: "Movie" },
  { word: "SPIDERMAN", category: "Movie" },
  { word: "WONDER WOMAN", category: "Movie" },
  { word: "FORREST GUMP", category: "Movie" },
  { word: "STAR WARS", category: "Movie" },
  { word: "HARRY POTTER", category: "Movie" },
  { word: "LION KING", category: "Movie" },
  { word: "TOY STORY", category: "Movie" },
  
  // Technology
  { word: "COMPUTER", category: "Technology" },
  { word: "INTERNET", category: "Technology" },
  { word: "SMARTPHONE", category: "Technology" },
  { word: "SOFTWARE", category: "Technology" },
  { word: "DATABASE", category: "Technology" },
  { word: "ALGORITHM", category: "Technology" },
  { word: "ENCRYPTION", category: "Technology" },
  { word: "BLUETOOTH", category: "Technology" },
  { word: "KEYBOARD", category: "Technology" },
  { word: "MONITOR", category: "Technology" },
  { word: "ROBOTICS", category: "Technology" },
  { word: "VIRTUAL", category: "Technology" },
  { word: "ARTIFICIAL", category: "Technology" },
  { word: "QUANTUM", category: "Technology" },
  { word: "BLOCKCHAIN", category: "Technology" },
  
  // Sports
  { word: "BASKETBALL", category: "Sport" },
  { word: "FOOTBALL", category: "Sport" },
  { word: "TENNIS", category: "Sport" },
  { word: "BASEBALL", category: "Sport" },
  { word: "SWIMMING", category: "Sport" },
  { word: "VOLLEYBALL", category: "Sport" },
  { word: "CRICKET", category: "Sport" },
  { word: "HOCKEY", category: "Sport" },
  { word: "GOLF", category: "Sport" },
  { word: "BOXING", category: "Sport" },
  { word: "CYCLING", category: "Sport" },
  { word: "GYMNASTICS", category: "Sport" },
  { word: "SKATEBOARD", category: "Sport" },
  { word: "SURFING", category: "Sport" },
  { word: "WRESTLING", category: "Sport" },
  
  // Nature
  { word: "MOUNTAIN", category: "Nature" },
  { word: "RAINBOW", category: "Nature" },
  { word: "WATERFALL", category: "Nature" },
  { word: "HURRICANE", category: "Nature" },
  { word: "EARTHQUAKE", category: "Nature" },
  { word: "VOLCANO", category: "Nature" },
  { word: "GLACIER", category: "Nature" },
  { word: "MEADOW", category: "Nature" },
  { word: "FOREST", category: "Nature" },
  { word: "DESERT", category: "Nature" },
  { word: "TSUNAMI", category: "Nature" },
  { word: "TORNADO", category: "Nature" },
  { word: "LIGHTNING", category: "Nature" },
  { word: "SUNSHINE", category: "Nature" },
  { word: "MOONLIGHT", category: "Nature" },
  
  // Music
  { word: "GUITAR", category: "Music" },
  { word: "PIANO", category: "Music" },
  { word: "VIOLIN", category: "Music" },
  { word: "DRUMS", category: "Music" },
  { word: "TRUMPET", category: "Music" },
  { word: "SAXOPHONE", category: "Music" },
  { word: "CELLO", category: "Music" },
  { word: "CLARINET", category: "Music" },
  { word: "TROMBONE", category: "Music" },
  { word: "HARMONICA", category: "Music" },
  { word: "ACCORDION", category: "Music" },
  { word: "XYLOPHONE", category: "Music" },
  { word: "MICROPHONE", category: "Music" },
  { word: "ORCHESTRA", category: "Music" },
  { word: "SYMPHONY", category: "Music" },
];

export function getRandomWord(): WordEntry {
  return WORD_LIST[Math.floor(Math.random() * WORD_LIST.length)];
}
